<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'CheckoutWC\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'CheckoutWC\\Symfony\\Polyfill\\Php73\\' => array($vendorDir . '/symfony/polyfill-php73'),
    'CheckoutWC\\Symfony\\Component\\RateLimiter\\' => array($vendorDir . '/symfony/rate-limiter'),
    'CheckoutWC\\Symfony\\Component\\OptionsResolver\\' => array($vendorDir . '/symfony/options-resolver'),
    'CheckoutWC\\Symfony\\Component\\Lock\\' => array($vendorDir . '/symfony/lock'),
    'CheckoutWC\\Symfony\\Component\\CssSelector\\' => array($vendorDir . '/symfony/css-selector'),
    'CheckoutWC\\StellarWP\\Installer\\Assets_JS\\' => array($vendorDir . '/stellarwp/installer/src/assets/js'),
    'CheckoutWC\\StellarWP\\Installer\\Admin_Views\\' => array($vendorDir . '/stellarwp/installer/src/admin-views'),
    'CheckoutWC\\StellarWP\\Installer\\' => array($vendorDir . '/stellarwp/installer/src/Installer'),
    'CheckoutWC\\Sabberworm\\CSS\\' => array($vendorDir . '/sabberworm/php-css-parser/src'),
    'CheckoutWC\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'CheckoutWC\\Pressmodo\\AdminNotices\\' => array($vendorDir . '/pressmodo/wp-admin-notices/src'),
    'CheckoutWC\\Pelago\\Emogrifier\\' => array($vendorDir . '/pelago/emogrifier/src'),
);
